### ISSUE TITLE
a way to contact the author

### ISSUE THREAD

**Issue by juliangruber** [juliangruber/dat.json#2]
should we leave the author field free form, to allow for something like `Julian Gruber <julian@juliangruber.com>` or `https://juliangruber.com` or `@juliangruber` etc, or should we standardize this more and have something like `.author.name` & `.author.email`?

**Comment by karissa** [comment]
i'd say lets not reinvent the wheel and use the way authors are described in this: http://specs.frictionlessdata.io/data-packages/#recommended-fields

the simplest way `"Joe Bloggs <joe@bloggs.com>"` also happens to be the same as it is in package.json files, so that's pretty convenient!

**Comment by juliangruber** [comment]
gotcha! how does this look? https://github.com/juliangruber/dat.json/blob/master/README.md

**Comment by joehand** [comment]
That looks good! Down the line, we may want to add the "contributors" or similar. Right now the author is the person that can write to the hyperdrive, but multiwriter may blur that line a bit.

That was one confusing thing when I was making some datapackages - I was the "author" but the data came from another source (so it wasn't actually my data).

**Comment by karissa** [comment]
yeah that makes sense.

**Comment by juliangruber** [comment]
great!
